# Configuración del servidor
server.address=0.0.0.0
server.port=${PORT:8080}
# Aca tengo dudas sobre el puerto 10000 que no estoy seguro si puede estar afectando el tema del health


# Configuración de la base de datos (PostgreSQL) con Neon
spring.datasource.url=jdbc:postgresql://ep-summer-leaf-ahdwcedy-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${BD_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

# HikariCP (optimizado)
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.leak-detection-threshold=60000


# SSL es obligatorio en Render
spring.datasource.hikari.data-source-properties.sslmode=require

# Configuración de Swagger/OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Otros
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# Aca estan las propierties del security y del "hackeo" para mantener viva la api
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration